import '../models/admin_model.dart';
import '../models/user_model.dart' as user_models;
import '../models/agent_model.dart' as agent_models;
import '../models/transaction_model.dart';

/// Mock Data Service
/// Provides realistic demo data for all screens
class MockDataService {
  // Singleton pattern
  static final MockDataService _instance = MockDataService._internal();
  factory MockDataService() => _instance;
  MockDataService._internal();

  // ==================== Current Admin ====================
  AdminModel get currentAdmin => AdminModel(
        id: 'admin-1',
        email: 'admin@tcc.sl',
        name: 'John Admin',
        role: AdminRole.superAdmin,
        permissions: [
          'users.manage',
          'agents.manage',
          'transactions.manage',
          'investments.manage',
          'settings.manage',
          'reports.view',
        ],
        createdAt: DateTime.now().subtract(const Duration(days: 365)),
        lastLogin: DateTime.now().subtract(const Duration(hours: 2)),
        isActive: true,
      );

  // ==================== Dashboard Stats ====================
  Map<String, dynamic> get dashboardStats => {
        'totalUsers': 15234,
        'totalAgents': 342,
        'totalTransactions': 45678,
        'totalRevenue': 125000000.0,
        'userGrowth': 12.5,
        'agentGrowth': 8.3,
        'transactionGrowth': 15.7,
        'revenueGrowth': 18.2,
        'pendingKyc': 28,
        'pendingWithdrawals': 15,
        'pendingDeposits': 12,
        'pendingAgentVerifications': 8,
      };

  // ==================== Users ====================
  List<user_models.UserModel> get users => [
        user_models.UserModel(
          id: 'user-1',
          email: 'john.doe@example.com',
          firstName: 'John',
          lastName: 'Doe',
          phone: '+232 76 123 4567',
          dateOfBirth: DateTime(1990, 5, 15),
          address: 'Freetown, Sierra Leone',
          kycStatus: user_models.KycStatus.approved,
          status: user_models.UserStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 120)),
          lastActive: DateTime.now().subtract(const Duration(hours: 3)),
          walletBalance: 150000.0,
          hasBankDetails: true,
          hasInvestments: true,
        ),
        user_models.UserModel(
          id: 'user-2',
          email: 'sarah.johnson@example.com',
          firstName: 'Sarah',
          lastName: 'Johnson',
          phone: '+232 77 234 5678',
          kycStatus: user_models.KycStatus.pending,
          status: user_models.UserStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
          lastActive: DateTime.now().subtract(const Duration(minutes: 30)),
          walletBalance: 50000.0,
          hasBankDetails: false,
          hasInvestments: false,
        ),
        user_models.UserModel(
          id: 'user-3',
          email: 'michael.brown@example.com',
          firstName: 'Michael',
          lastName: 'Brown',
          phone: '+232 78 345 6789',
          kycStatus: user_models.KycStatus.approved,
          status: user_models.UserStatus.active,
          createdAt: DateTime.now().subtract(const Duration(days: 45)),
          lastActive: DateTime.now().subtract(const Duration(hours: 5)),
          walletBalance: 320000.0,
          hasBankDetails: true,
          hasInvestments: true,
        ),
        user_models.UserModel(
          id: 'user-4',
          email: 'emma.wilson@example.com',
          firstName: 'Emma',
          lastName: 'Wilson',
          phone: '+232 79 456 7890',
          kycStatus: user_models.KycStatus.rejected,
          status: user_models.UserStatus.inactive,
          createdAt: DateTime.now().subtract(const Duration(days: 10)),
          lastActive: DateTime.now().subtract(const Duration(days: 3)),
          walletBalance: 5000.0,
          hasBankDetails: false,
          hasInvestments: false,
        ),
        user_models.UserModel(
          id: 'user-5',
          email: 'david.taylor@example.com',
          firstName: 'David',
          lastName: 'Taylor',
          phone: '+232 76 567 8901',
          kycStatus: user_models.KycStatus.pending,
          status: user_models.UserStatus.active,
          createdAt: DateTime.now().subtract(const Duration(hours: 5)),
          lastActive: DateTime.now().subtract(const Duration(minutes: 10)),
          walletBalance: 0.0,
          hasBankDetails: false,
          hasInvestments: false,
        ),
      ];

  // ==================== Agents ====================
  List<agent_models.AgentModel> get agents => [
        agent_models.AgentModel(
          id: 'agent-1',
          email: 'agent.freetown@tcc.sl',
          firstName: 'Mohamed',
          lastName: 'Kamara',
          phone: '+232 76 111 2222',
          location: 'Freetown',
          address: 'Lumley, Freetown',
          businessName: 'Kamara Money Services',
          businessRegistrationNumber: 'BRN-2022-00145',
          status: agent_models.AgentStatus.active,
          verificationStatus: agent_models.KycStatus.approved,
          commissionRate: 0.5,
          totalCommissionEarned: 2500000.0,
          totalTransactions: 1250,
          walletBalance: 500000.0,
          isAvailable: true,
          createdAt: DateTime.now().subtract(const Duration(days: 180)),
          lastActive: DateTime.now().subtract(const Duration(minutes: 15)),
          hasBankDetails: true,
        ),
        agent_models.AgentModel(
          id: 'agent-2',
          email: 'agent.bo@tcc.sl',
          firstName: 'Fatmata',
          lastName: 'Sesay',
          phone: '+232 77 222 3333',
          location: 'Bo',
          address: 'Bo Town Center',
          businessName: 'Sesay Financial Services',
          businessRegistrationNumber: 'BRN-2022-00289',
          status: agent_models.AgentStatus.active,
          verificationStatus: agent_models.KycStatus.approved,
          commissionRate: 0.5,
          totalCommissionEarned: 1800000.0,
          totalTransactions: 920,
          walletBalance: 350000.0,
          isAvailable: true,
          createdAt: DateTime.now().subtract(const Duration(days: 150)),
          lastActive: DateTime.now().subtract(const Duration(hours: 1)),
          hasBankDetails: true,
        ),
        agent_models.AgentModel(
          id: 'agent-3',
          email: 'agent.kenema@tcc.sl',
          firstName: 'Aminata',
          lastName: 'Koroma',
          phone: '+232 78 333 4444',
          location: 'Kenema',
          address: 'Kenema City',
          businessName: 'Koroma Trading & Services',
          businessRegistrationNumber: 'BRN-2023-00123',
          status: agent_models.AgentStatus.inactive,
          verificationStatus: agent_models.KycStatus.approved,
          commissionRate: 0.5,
          totalCommissionEarned: 950000.0,
          totalTransactions: 480,
          walletBalance: 120000.0,
          isAvailable: false,
          createdAt: DateTime.now().subtract(const Duration(days: 90)),
          lastActive: DateTime.now().subtract(const Duration(days: 5)),
          hasBankDetails: true,
        ),
        agent_models.AgentModel(
          id: 'agent-4',
          email: 'new.agent@tcc.sl',
          firstName: 'Ibrahim',
          lastName: 'Conteh',
          phone: '+232 79 444 5555',
          location: 'Makeni',
          address: 'Makeni Town',
          businessName: 'Conteh Express Services',
          businessRegistrationNumber: 'BRN-2024-00001',
          status: agent_models.AgentStatus.inactive,
          verificationStatus: agent_models.KycStatus.pending,
          commissionRate: 0.5,
          totalCommissionEarned: 0.0,
          totalTransactions: 0,
          walletBalance: 0.0,
          isAvailable: false,
          createdAt: DateTime.now().subtract(const Duration(hours: 12)),
          hasBankDetails: true,
        ),
      ];

  // ==================== Transactions ====================
  List<TransactionModel> get transactions => [
        TransactionModel(
          id: 'txn-1',
          userId: 'user-1',
          userName: 'John Doe',
          type: TransactionType.deposit,
          amount: 100000.0,
          fee: 0.0,
          total: 100000.0,
          status: TransactionStatus.completed,
          paymentMethod: 'Bank Transfer',
          agentId: 'agent-1',
          agentName: 'Mohamed Kamara',
          description: 'Deposit via Bank Transfer',
          createdAt: DateTime.now().subtract(const Duration(hours: 2)),
          completedAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 55)),
        ),
        TransactionModel(
          id: 'txn-2',
          userId: 'user-2',
          userName: 'Sarah Johnson',
          type: TransactionType.deposit,
          amount: 50000.0,
          fee: 0.0,
          total: 50000.0,
          status: TransactionStatus.pending,
          paymentMethod: 'Agent',
          description: 'Deposit via Agent - Awaiting Approval',
          createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
        ),
        TransactionModel(
          id: 'txn-3',
          userId: 'user-3',
          userName: 'Michael Brown',
          type: TransactionType.withdrawal,
          amount: 80000.0,
          fee: 1600.0,
          total: 81600.0,
          status: TransactionStatus.pending,
          paymentMethod: 'Bank Transfer',
          description: 'Withdrawal to Bank Account',
          createdAt: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        TransactionModel(
          id: 'txn-4',
          userId: 'user-1',
          userName: 'John Doe',
          type: TransactionType.transfer,
          amount: 20000.0,
          fee: 200.0,
          total: 20200.0,
          status: TransactionStatus.completed,
          paymentMethod: 'Wallet',
          description: 'Transfer to Sarah Johnson',
          createdAt: DateTime.now().subtract(const Duration(hours: 5)),
          completedAt: DateTime.now().subtract(const Duration(hours: 5)),
        ),
        TransactionModel(
          id: 'txn-5',
          userId: 'user-3',
          userName: 'Michael Brown',
          type: TransactionType.billPayment,
          amount: 15000.0,
          fee: 225.0,
          total: 15225.0,
          status: TransactionStatus.completed,
          paymentMethod: 'Wallet',
          description: 'Electricity Bill Payment - EDSA',
          createdAt: DateTime.now().subtract(const Duration(hours: 8)),
          completedAt: DateTime.now().subtract(const Duration(hours: 8)),
        ),
        TransactionModel(
          id: 'txn-6',
          userId: 'user-1',
          userName: 'John Doe',
          type: TransactionType.investment,
          amount: 200000.0,
          fee: 0.0,
          total: 200000.0,
          status: TransactionStatus.completed,
          paymentMethod: 'Wallet',
          description: 'Investment - Agriculture (12 months)',
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
          completedAt: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TransactionModel(
          id: 'txn-7',
          userId: 'user-2',
          userName: 'Sarah Johnson',
          type: TransactionType.voting,
          amount: 1000.0,
          fee: 0.0,
          total: 1000.0,
          status: TransactionStatus.completed,
          paymentMethod: 'Wallet',
          description: 'Vote - Community Development Poll',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          completedAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        TransactionModel(
          id: 'txn-8',
          userId: 'user-3',
          userName: 'Michael Brown',
          type: TransactionType.deposit,
          amount: 150000.0,
          fee: 0.0,
          total: 150000.0,
          status: TransactionStatus.failed,
          paymentMethod: 'Mobile Money',
          description: 'Deposit via Mobile Money - Failed',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
        ),
      ];

  // ==================== Investments ====================
  List<Map<String, dynamic>> get investments => [
        {
          'id': 'inv-1',
          'userId': 'user-1',
          'userName': 'John Doe',
          'category': 'AGRICULTURE',
          'subCategory': 'Rice Farming',
          'unitType': 'PLOT',
          'amountInvested': 200000.0,
          'tenure': 12,
          'expectedReturn': 10.0,
          'expectedReturnAmount': 20000.0,
          'startDate': DateTime.now().subtract(const Duration(days: 150)),
          'maturityDate': DateTime.now().add(const Duration(days: 215)),
          'status': 'ONGOING',
          'progress': 41.0,
        },
        {
          'id': 'inv-2',
          'userId': 'user-3',
          'userName': 'Michael Brown',
          'category': 'MINERALS',
          'subCategory': 'Gold Mining',
          'unitType': 'LOT',
          'amountInvested': 500000.0,
          'tenure': 24,
          'expectedReturn': 30.0,
          'expectedReturnAmount': 150000.0,
          'startDate': DateTime.now().subtract(const Duration(days: 720)),
          'maturityDate': DateTime.now().subtract(const Duration(days: 5)),
          'status': 'MATURED',
          'progress': 100.0,
        },
        {
          'id': 'inv-3',
          'userId': 'user-1',
          'userName': 'John Doe',
          'category': 'EDUCATION',
          'subCategory': 'School Infrastructure',
          'unitType': 'PLOT',
          'amountInvested': 300000.0,
          'tenure': 6,
          'expectedReturn': 6.0,
          'expectedReturnAmount': 18000.0,
          'startDate': DateTime.now().subtract(const Duration(days: 180)),
          'maturityDate': DateTime.now().add(const Duration(days: 5)),
          'status': 'ONGOING',
          'progress': 97.0,
        },
      ];

  // ==================== E-Voting Polls ====================
  List<Map<String, dynamic>> get polls => [
        {
          'id': 'poll-1',
          'title': 'Community Development Project 2025',
          'question': 'Which development project should the community prioritize?',
          'options': [
            {'id': 'opt-1', 'text': 'Build New School', 'votes': 245},
            {'id': 'opt-2', 'text': 'Improve Water Supply', 'votes': 312},
            {'id': 'opt-3', 'text': 'Road Construction', 'votes': 178},
            {'id': 'opt-4', 'text': 'Health Center Upgrade', 'votes': 201},
          ],
          'votingCharge': 1000.0,
          'status': 'ACTIVE',
          'startDate': DateTime.now().subtract(const Duration(days: 5)),
          'endDate': DateTime.now().add(const Duration(days: 10)),
          'totalVotes': 936,
          'totalRevenue': 936000.0,
        },
        {
          'id': 'poll-2',
          'title': 'Best Community Leader 2024',
          'question': 'Who do you think was the most effective community leader this year?',
          'options': [
            {'id': 'opt-1', 'text': 'Mohamed Kamara', 'votes': 156},
            {'id': 'opt-2', 'text': 'Fatmata Sesay', 'votes': 189},
            {'id': 'opt-3', 'text': 'Ibrahim Conteh', 'votes': 123},
          ],
          'votingCharge': 500.0,
          'status': 'ENDED',
          'startDate': DateTime.now().subtract(const Duration(days: 30)),
          'endDate': DateTime.now().subtract(const Duration(days: 15)),
          'totalVotes': 468,
          'totalRevenue': 234000.0,
        },
        {
          'id': 'poll-3',
          'title': 'New Year Celebration Plans',
          'question': 'How should we celebrate the New Year?',
          'options': [
            {'id': 'opt-1', 'text': 'Community Feast', 'votes': 0},
            {'id': 'opt-2', 'text': 'Music Festival', 'votes': 0},
            {'id': 'opt-3', 'text': 'Sports Tournament', 'votes': 0},
          ],
          'votingCharge': 2000.0,
          'status': 'DRAFT',
          'startDate': DateTime.now().add(const Duration(days: 20)),
          'endDate': DateTime.now().add(const Duration(days: 35)),
          'totalVotes': 0,
          'totalRevenue': 0.0,
        },
      ];

  // ==================== Recent Activity ====================
  List<Map<String, dynamic>> get recentActivity => [
        {
          'type': 'KYC_APPROVAL',
          'message': 'KYC approved for John Doe',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 5)),
          'icon': 'check_circle',
          'color': 'success',
        },
        {
          'type': 'WITHDRAWAL_PENDING',
          'message': 'New withdrawal request from Michael Brown (TCC 80,000)',
          'timestamp': DateTime.now().subtract(const Duration(hours: 1)),
          'icon': 'payments',
          'color': 'warning',
        },
        {
          'type': 'AGENT_VERIFICATION',
          'message': 'New agent verification request from Ibrahim Conteh',
          'timestamp': DateTime.now().subtract(const Duration(hours: 12)),
          'icon': 'person_add',
          'color': 'info',
        },
        {
          'type': 'DEPOSIT_PENDING',
          'message': 'Deposit pending approval for Sarah Johnson (TCC 50,000)',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 30)),
          'icon': 'account_balance',
          'color': 'warning',
        },
        {
          'type': 'INVESTMENT_MATURED',
          'message': 'Investment matured for Michael Brown (TCC 500,000)',
          'timestamp': DateTime.now().subtract(const Duration(days: 5)),
          'icon': 'trending_up',
          'color': 'success',
        },
      ];

  // ==================== Chart Data ====================
  Map<String, dynamic> get chartData => {
        'transactionTrend': [
          {'date': '2025-01-01', 'deposits': 850, 'withdrawals': 320, 'transfers': 450},
          {'date': '2025-01-02', 'deposits': 920, 'withdrawals': 380, 'transfers': 520},
          {'date': '2025-01-03', 'deposits': 780, 'withdrawals': 290, 'transfers': 410},
          {'date': '2025-01-04', 'deposits': 1100, 'withdrawals': 450, 'transfers': 680},
          {'date': '2025-01-05', 'deposits': 950, 'withdrawals': 360, 'transfers': 550},
          {'date': '2025-01-06', 'deposits': 1050, 'withdrawals': 420, 'transfers': 620},
          {'date': '2025-01-07', 'deposits': 890, 'withdrawals': 340, 'transfers': 480},
        ],
        'revenueByCategory': [
          {'category': 'Withdrawal Fees', 'amount': 2500000.0},
          {'category': 'Transfer Fees', 'amount': 1800000.0},
          {'category': 'Bill Payment Fees', 'amount': 1200000.0},
          {'category': 'E-Voting', 'amount': 500000.0},
        ],
        'investmentDistribution': [
          {'category': 'Agriculture', 'percentage': 45.0, 'amount': 56250000.0},
          {'category': 'Minerals', 'percentage': 35.0, 'amount': 43750000.0},
          {'category': 'Education', 'percentage': 20.0, 'amount': 25000000.0},
        ],
      };
}
